function [kratios, bounds] = ev_condition_taylor(d, polysize, ...
    nodegen, polygen, evgen, pkmean, pkwidth, boundgens)
% Taylor eigenvalue condition number bound test function.
% Use this function from the generic_ev_test script.

    [kratios, bounds] = ev_generic_condition( ...
        @std_xchg_taylor_monomial, @basiseval_taylor, ...
        d, polysize, nodegen, polygen, evgen, pkmean, pkwidth, boundgens);
end
